version: '3'
services:
  spark-master:
    image: gq-env/spark-master:3.2.0-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker:
    image: gq-env/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker
    deploy:
      replicas: 5
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
